# Generated by Django 4.2.16 on 2025-04-06 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0002_remove_recommendation_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationlike',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_likes', to='recommendations.recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendationlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
