# Generated by Django 4.2.16 on 2025-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default='', max_length=100),
        ),
    ]
