# Generated by Django 4.2.16 on 2025-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_author_book_authors_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
